# Generated by Django 2.1.4 on 2018-12-10 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
    ]
